backend/build.gradle, backend/src/main/java/ssu/groupstudy/domain/auth/api/AuthApi.java, backend/src/main/java/ssu/groupstudy/domain/auth/service/AuthService.java, backend/src/main/java/ssu/groupstudy/domain/notification/api/NotificationApi.java, backend/src/main/java/ssu/groupstudy/domain/notification/service/NotificationService.java, backend/src/main/java/ssu/groupstudy/domain/user/domain/FcmToken.java, backend/src/main/java/ssu/groupstudy/domain/user/domain/User.java, backend/src/main/java/ssu/groupstudy/domain/user/dto/request/SignInRequest.java, backend/src/main/java/ssu/groupstudy/global/util/FcmUtils.java, backend/src/test/java/ssu/groupstudy/domain/auth/service/AuthServiceTest.java, backend/src/test/java/ssu/groupstudy/domain/common/ServiceTest.java, backend/src/test/resources/sql/create.sql
멀티캐스팅을 통해 스터디원 콕찌르기 구현 완료
테스트용으로 일단 push 해보겠습니다
=> [B] feat: 스터디원 콕찌르기 구현

backend/src/main/java/ssu/groupstudy/domain/study/api/ParticipantApi.java, backend/src/main/java/ssu/groupstudy/domain/study/domain/Study.java, backend/src/main/java/ssu/groupstudy/domain/study/dto/DoneCount.java, backend/src/main/java/ssu/groupstudy/domain/study/dto/StatusTagInfo.java, backend/src/main/java/ssu/groupstudy/domain/study/dto/response/ParticipantResponse.java, backend/src/main/java/ssu/groupstudy/domain/study/repository/ParticipantRepository.java, backend/src/main/java/ssu/groupstudy/domain/study/repository/StudyRepository.java, backend/src/main/java/ssu/groupstudy/domain/study/service/ParticipantsService.java, backend/src/test/java/ssu/groupstudy/domain/study/dto/DoneCountTest.java, backend/src/test/java/ssu/groupstudy/domain/study/repository/ParticipantRepositoryTest.java, backend/src/test/java/ssu/groupstudy/domain/study/repository/StudyRepositoryTest.java, backend/src/test/resources/sql/insert.sql
=> [B] 스터디 참여자의 프로필 상세보기 API 구현

backend/src/main/java/ssu/groupstudy/domain/study/dto/StatusTagInfo.java, backend/src/main/java/ssu/groupstudy/domain/study/dto/StudyColorInfo.java, backend/src/main/java/ssu/groupstudy/domain/study/dto/response/ParticipantResponse.java, backend/src/main/java/ssu/groupstudy/domain/study/repository/ParticipantRepository.java, backend/src/main/java/ssu/groupstudy/domain/study/service/ParticipantsService.java, backend/src/test/java/ssu/groupstudy/domain/study/repository/ParticipantRepositoryTest.java
=> [B] feat: 참여자 프로필 상세 보기 수정

backend/src/main/java/ssu/groupstudy/domain/auth/api/AuthApi.java, backend/src/main/java/ssu/groupstudy/domain/notice/domain/Notice.java, backend/src/main/java/ssu/groupstudy/domain/round/domain/Appointment.java, backend/src/main/java/ssu/groupstudy/domain/round/domain/Round.java, backend/src/main/java/ssu/groupstudy/domain/round/dto/request/AppointmentRequest.java, backend/src/main/java/ssu/groupstudy/domain/round/repository/RoundRepository.java, backend/src/main/java/ssu/groupstudy/domain/study/domain/Participant.java, backend/src/main/java/ssu/groupstudy/domain/study/repository/ParticipantRepository.java, backend/src/main/java/ssu/groupstudy/domain/study/service/ParticipantsService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyService.java, backend/src/main/java/ssu/groupstudy/domain/task/dto/response/TaskResponse.java, backend/src/main/java/ssu/groupstudy/domain/user/api/UserApi.java, backend/src/main/java/ssu/groupstudy/global/config/SecurityConfig.java, backend/src/test/java/ssu/groupstudy/domain/round/repository/RoundRepositoryTest.java, backend/src/test/java/ssu/groupstudy/domain/study/service/StudyServiceTest.java
+ 값객체인 Appointment 객체 NPE 관련 버그 수정
+ 초대 받는 경우 기본 값 지정 구현
=> [B] feat: 기본 회차에 과제 추가하도록 구현

backend/src/main/java/ssu/groupstudy/domain/study/dto/response/StudyInfoResponse.java
=> [B] feat: 홈화면 조회 API 내에 detail 필드 추가

backend/src/main/java/ssu/groupstudy/domain/round/domain/Round.java, backend/src/main/java/ssu/groupstudy/domain/round/repository/RoundRepository.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyInviteService.java, backend/src/main/java/ssu/groupstudy/global/handler/GlobalExceptionHandler.java
1. 스터디 초대 시에 사용자를 미래 회차에 추가 함
2. 스터디 탈퇴 후 다시 입장하는 경우 회차에 중복 추가됨
3. 에러 발생
=> Set 자료구조가 아닌 List 쓰는 것이 불가피하므로 add 할 때 존재 여부 검사 로직을 추가했음
=> [B] fix: 스터디 초대 관련 버그 수정

backend/src/main/java/ssu/groupstudy/domain/comment/service/CommentService.java, backend/src/main/java/ssu/groupstudy/domain/notice/repository/NoticeRepository.java, backend/src/main/java/ssu/groupstudy/domain/notice/service/NoticeService.java, backend/src/main/java/ssu/groupstudy/domain/notification/domain/event/push/CommentCreationEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/domain/event/push/NoticeCreationEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/domain/event/unsubscribe/NoticeTopicUnsubscribeEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/domain/event/unsubscribe/StudyTopicUnsubscribeEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/listener/PushListener.java, backend/src/main/java/ssu/groupstudy/domain/notification/listener/SubscribeListener.java, backend/src/main/java/ssu/groupstudy/domain/study/service/NoticeTopicUnsubscribeEvent.java, backend/src/main/java/ssu/groupstudy/domain/study/service/ParticipantsService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyInviteService.java, backend/src/main/java/ssu/groupstudy/global/util/FcmUtils.java, backend/src/test/java/ssu/groupstudy/domain/notice/repository/NoticeRepositoryTest.java, backend/src/test/java/ssu/groupstudy/domain/study/service/StudyInviteServiceTest.java
* 공지사항 작성 시 스터디원에게 알림 가도록 구현
* 공지사항에 댓글 작성 시 해당 토픽에 알림 가도록 구현
* 스터디 탈퇴 및 추방 시에 관련 알림 삭제 구현
=> [B] feat: 공지사항 알림 기능 추가

frontend/ios/Runner.xcodeproj/project.pbxproj, frontend/lib/l10n/app_ko.arb, frontend/lib/models/sign_info.dart, frontend/lib/routes/home_route.dart, frontend/lib/routes/sign_routes/sign_in_route.dart, frontend/lib/routes/sign_routes/sign_up_detail_route.dart, frontend/lib/routes/splash_route.dart, frontend/lib/routes/studies/study_detail_route.dart, frontend/lib/services/auth.dart, frontend/lib/services/message_service.dart, frontend/pubspec.yaml
* [F] chore: 1.0.3+4 setting
* [F] feat: FCM Token 검증 로직 추가
* [F] feat: 이름 유효성 검사 추가
* [F] feat: 홈화면 API 개선
* [F] bugfix: 안드로이드 스터디 홈 화면 상단 색상이 보이지 않는 버그 임시 해결
=> [F] deploy: v1.0.3

backend/src/main/java/ssu/groupstudy/domain/round/domain/Round.java, backend/src/main/java/ssu/groupstudy/domain/study/domain/Participant.java, backend/src/main/java/ssu/groupstudy/domain/study/domain/Participants.java, backend/src/main/java/ssu/groupstudy/domain/study/domain/Study.java, backend/src/main/java/ssu/groupstudy/domain/study/service/ParticipantsService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyInviteService.java, backend/src/main/java/ssu/groupstudy/global/constant/Color.java, backend/src/main/java/ssu/groupstudy/global/constant/ResultCode.java, backend/src/test/java/ssu/groupstudy/domain/study/repository/ParticipantRepositoryTest.java, backend/src/test/java/ssu/groupstudy/domain/study/service/StudyInviteServiceTest.java, backend/src/test/java/ssu/groupstudy/domain/study/service/StudyServiceTest.java
- 스터디 초대 시에 방장의 스터디 색상을 기본으로 채택하도록 로직 추가
=> [B] feat: 스터디 초대 시에 방장의 스터디 색상을 기본으로 채택하도록 로직 추가

frontend/lib/utilities/lazy_update_controller.dart, frontend/lib/widgets/tasks/task_check_box.dart, frontend/lib/widgets/tasks/task_group_widget.dart, frontend/lib/widgets/tasks/task_widget.dart
과제 체크시 즉시 반영이 아닌 일정 시간이 지난 후 반영
대기 시간: 3초
=> [F] feat: 과제 lazy update (#184)

backend/src/main/java/ssu/groupstudy/domain/auth/service/AuthService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/ExampleStudyCreateService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyInviteService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyService.java, backend/src/main/java/ssu/groupstudy/domain/user/api/UserApi.java, backend/src/main/java/ssu/groupstudy/domain/user/domain/User.java, backend/src/main/java/ssu/groupstudy/domain/user/service/UserService.java, backend/src/main/java/ssu/groupstudy/global/util/ImageManager.java, backend/src/test/java/ssu/groupstudy/domain/auth/service/AuthServiceTest.java, backend/src/test/java/ssu/groupstudy/domain/study/service/StudyServiceTest.java
- 개발서버에서 사용자, 스터디 이미지 정상 업로드 되는지 확인
=> [B] feat: 예시 스터디 생성, activateDate 갱신 API 구현

backend/src/main/java/ssu/groupstudy/domain/auth/domain/Authority.java, backend/src/main/java/ssu/groupstudy/domain/auth/security/jwt/JwtProvider.java, backend/src/main/java/ssu/groupstudy/domain/auth/service/AuthService.java, backend/src/main/java/ssu/groupstudy/domain/notification/constants/ChannelCode.java, backend/src/main/java/ssu/groupstudy/domain/notification/constants/TopicCode.java, backend/src/main/java/ssu/groupstudy/domain/notification/domain/FcmToken.java, backend/src/main/java/ssu/groupstudy/domain/notification/listener/PushListener.java, backend/src/main/java/ssu/groupstudy/domain/notification/listener/SubscribeListener.java, backend/src/main/java/ssu/groupstudy/domain/notification/repository/FcmTokenRepository.java, backend/src/main/java/ssu/groupstudy/domain/notification/scheduler/TokenScheduler.java, backend/src/main/java/ssu/groupstudy/domain/round/repository/RoundRepository.java, backend/src/main/java/ssu/groupstudy/domain/round/service/RoundService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/ExampleStudyCreateService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyInviteService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyService.java, backend/src/main/java/ssu/groupstudy/domain/user/api/UserApi.java, backend/src/main/java/ssu/groupstudy/domain/user/domain/User.java, backend/src/main/java/ssu/groupstudy/domain/user/service/UserService.java, backend/src/main/java/ssu/groupstudy/global/config/SchedulerConfig.java, backend/src/main/java/ssu/groupstudy/global/constant/ResultCode.java, backend/src/main/java/ssu/groupstudy/global/handler/GlobalExceptionHandler.java, backend/src/main/java/ssu/groupstudy/global/openfeign/NotionOpenFeign.java, backend/src/main/java/ssu/groupstudy/global/util/FcmUtils.java, backend/src/main/java/ssu/groupstudy/global/util/ImageManager.java, backend/src/test/java/ssu/groupstudy/domain/auth/service/AuthServiceTest.java, backend/src/test/java/ssu/groupstudy/domain/notification/domain/TopicCodeTest.java, backend/src/test/java/ssu/groupstudy/domain/round/repository/RoundRepositoryTest.java, backend/src/test/java/ssu/groupstudy/domain/round/service/RoundServiceTest.java, backend/src/test/java/ssu/groupstudy/domain/study/service/StudyServiceTest.java
- 회차 생성 개수 제한 구현
- 만료 fcm 토큰 정기 삭제 구현 (spring scheduler)
- 스터디 초대 시 기본 색상 구현
- activateDate API 구현
- 회원가입 시 예시 스터디 생성
=> [B] deploy: v1.0.4

frontend/lib/l10n/app_ko.arb, frontend/lib/models/round.dart, frontend/lib/widgets/rounds/round_summary_list_widget.dart
=> [F] feat: 회차 최대 개수 제한

frontend/lib/widgets/rounds/round_summary_list_widget.dart, frontend/lib/widgets/rounds/round_summary_widget.dart
[F] feat : 회차 날짜 변경 시 회차 재정렬 요청 #186
=> [F] feat: 회차 시간 수정 리프레시 

backend/src/main/java/ssu/groupstudy/domain/notification/api/NotificationApi.java, backend/src/main/java/ssu/groupstudy/domain/notification/domain/event/push/CommentCreationEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/domain/event/push/NoticeCreationEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/listener/PushListener.java, backend/src/main/java/ssu/groupstudy/domain/notification/listener/SubscribeListener.java, backend/src/main/java/ssu/groupstudy/domain/notification/service/NotificationService.java, backend/src/main/java/ssu/groupstudy/global/util/StringUtils.java
* [B] refactor: 로그 호출 위치 변경
* [B] refactor: 알림 메세지 일괄 변경
=> [B] refactor : 알림 문구 변경 (#212)

backend/src/main/java/ssu/groupstudy/domain/auth/entity/AuthorityEntity.java, backend/src/main/java/ssu/groupstudy/domain/feedback/entity/FeedbackEntity.java, backend/src/main/java/ssu/groupstudy/domain/notice/entity/CheckNoticeEntity.java, backend/src/main/java/ssu/groupstudy/domain/notification/entity/FcmTokenEntity.java, backend/src/main/java/ssu/groupstudy/domain/round/entity/RoundParticipantEntity.java, backend/src/main/java/ssu/groupstudy/domain/task/entity/TaskEntity.java, backend/src/test/resources/sql/create.sql, backend/src/test/resources/sql/insert.sql
=> #219 시스템 칼럼 각 테이블에 추가

frontend/lib/services/database_service.dart, frontend/pubspec.yaml
=> [FE] deploy: v1.0.5

backend/src/main/java/ssu/groupstudy/api/comment/controller/CommentController.java, backend/src/main/java/ssu/groupstudy/api/notice/controller/NoticeController.java, backend/src/main/java/ssu/groupstudy/api/study/controller/ParticipantController.java, backend/src/main/java/ssu/groupstudy/api/task/controller/TaskController.java, backend/src/main/java/ssu/groupstudy/domain/comment/service/CommentService.java, backend/src/main/java/ssu/groupstudy/domain/notice/service/NoticeService.java, backend/src/main/java/ssu/groupstudy/domain/notification/event/push/CommentCreationEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/event/push/NoticeCreationEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/event/push/TaskDoneEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/event/subscribe/AllUserTopicSubscribeEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/event/subscribe/NoticeTopicSubscribeEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/event/subscribe/StudyTopicSubscribeEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/event/unsubscribe/NoticeTopicUnsubscribeEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/event/unsubscribe/StudyTopicUnsubscribeEvent.java, backend/src/main/java/ssu/groupstudy/domain/notification/listener/PushListener.java, backend/src/main/java/ssu/groupstudy/domain/notification/listener/SubscribeListener.java, backend/src/main/java/ssu/groupstudy/domain/notification/service/FcmTopicSubscribeService.java, backend/src/main/java/ssu/groupstudy/domain/notification/service/NotificationService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/ParticipantsService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyInviteService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyService.java, backend/src/main/java/ssu/groupstudy/domain/task/service/TaskService.java, backend/src/main/java/ssu/groupstudy/domain/user/entity/UserEntity.java, backend/src/test/java/ssu/groupstudy/domain/comment/service/CommentServiceTest.java, backend/src/test/java/ssu/groupstudy/domain/notice/service/NoticeServiceTest.java, backend/src/test/java/ssu/groupstudy/domain/study/service/StudyInviteServiceTest.java, backend/src/test/java/ssu/groupstudy/domain/task/service/TaskServiceTest.java
=> #242 Fcm 알림 비동기 처리 관련 에러 해결

frontend/lib/l10n/app_ko.arb
- 문구 수정
+ 변경 전 : 자세한 기록을 적어주세요
+ 변경 후 : 스터디원 모두가 볼 수 있는 기록이에요
=> [FE] #229 기록 가이드 문구 수정

frontend/lib/utilities/lazy_update_controller.dart, frontend/lib/widgets/tasks/task_check_box.dart
- 사용하지 않게된 lazy_update_controller는 deprecated 처리
=> [FE] #226 과제 체크박스의 lazy update 제거

backend/src/main/java/ssu/groupstudy/api/comment/controller/CommentController.java, backend/src/main/java/ssu/groupstudy/api/comment/vo/CreateCommentV2ReqVo.java, backend/src/main/java/ssu/groupstudy/api/common/vo/IdResVo.java, backend/src/main/java/ssu/groupstudy/api/notification/controller/NotificationController.java, backend/src/main/java/ssu/groupstudy/domain/auth/service/AuthService.java, backend/src/main/java/ssu/groupstudy/domain/comment/entity/CommentEntity.java, backend/src/main/java/ssu/groupstudy/domain/comment/service/CommentService.java, backend/src/main/java/ssu/groupstudy/domain/notification/param/NotificationCommentParam.java, backend/src/main/java/ssu/groupstudy/domain/notification/param/NotificationParam.java, backend/src/main/java/ssu/groupstudy/domain/notification/service/NotificationCommentService.java, backend/src/main/java/ssu/groupstudy/domain/notification/service/NotificationParticipantService.java, backend/src/main/java/ssu/groupstudy/domain/notification/service/NotificationService.java, backend/src/main/java/ssu/groupstudy/domain/notification/service/NotificationSubscribeService.java, backend/src/test/java/ssu/groupstudy/domain/auth/service/AuthServiceTest.java
=> #251 토큰 삭제 시에 예외처리 삭제

frontend/lib/services/message_service.dart
For more infromation, read #259
=> #259 Fix getFCMToken

frontend/lib/services/message_service.dart, frontend/lib/utilities/lazy_update_controller.dart, frontend/lib/widgets/tasks/task_check_box.dart, frontend/pubspec.yaml
- #226 Lazy Update 제거
- #259 알림이 오지 않는 버그 개선 (getFCMToken() 개선)
=> [FE] 1.0.7+8 배포

frontend/lib/routes/notices/notice_detail_route.dart
=> [FE] #250 Add dot to writing info of Notice Detail Route

backend/src/main/java/ssu/groupstudy/api/study/controller/ParticipantController.java, backend/src/main/java/ssu/groupstudy/domain/notification/service/FcmTokenService.java, backend/src/main/java/ssu/groupstudy/domain/notification/service/NotificationSubscribeService.java, backend/src/main/java/ssu/groupstudy/domain/study/repository/ParticipantEntityRepository.java, backend/src/main/java/ssu/groupstudy/domain/study/service/ParticipantsService.java, backend/src/main/java/ssu/groupstudy/domain/study/service/StudyService.java, backend/src/main/java/ssu/groupstudy/domain/user/service/UserService.java
회원 탈퇴 시 스터디 참여자에서도 제외되도록 로직 추가
=> #244 회원 탈퇴 시 스터디 참여자에서도 제외되도록 로직 추가

frontend/lib/routes/profiles/profile_route.dart, frontend/lib/widgets/comment_widget.dart, frontend/lib/widgets/line_profiles/participant_profile_widget.dart, frontend/lib/widgets/profile_lists/member_profile_list_widget.dart, frontend/lib/widgets/profile_lists/participant_profile_list_widget.dart
- Add Routing function for Profile Route
- Apply this to
+ comment_widget
+ participant_profile_widget
+ member_profile_widget
+ participant_profile_widget
=> #244 Handling exception on Profile Route
